// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpmjsbonkbiapbxzwqyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwbWpzYm9ua2JpYXBieHp3cXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NTg0MjMsImV4cCI6MjA2NzUzNDQyM30.5XC42MmWrUF2oMkfkIXPOzwa0z0Qmw00qFzO2FHHytE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});